spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microserviceconfig-test-dev
---
spring:
  profiles: default
  application:
    name: microserviceconfig-test-default
    